// <auto-generated />
using System;
using HomeAgency.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeAgency.Infrastructure.Migrations
{
    [DbContext(typeof(HomeAgencyDbContext))]
    [Migration("20240327193147_AddVillaTable")]
    partial class AddVillaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeAgency.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is a great villa",
                            Name = "LasVegas Mantion",
                            Occupancy = 0,
                            Price = 99.900000000000006,
                            Sqft = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is a great villa",
                            Name = "NewYork Mantion",
                            Occupancy = 0,
                            Price = 99.900000000000006,
                            Sqft = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "This is a great villa",
                            Name = "LasVegas Mantion",
                            Occupancy = 0,
                            Price = 99.900000000000006,
                            Sqft = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
